server:
  port: 7000


#mybatis mapping\u6587\u4EF6\u4F4D\u7F6E\u914D\u7F6E
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

######datasource######
###spring boot\u81EA\u52A8\u914D\u7F6E\u5355\u6570\u636E\u6E90###
#spring:
#   datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      type: com.alibaba.druid.pool.DruidDataSource
#      url: jdbc:mysql://172.16.11.9:3306/db_one?characterEncoding=utf8&useSSL=false
#      username: root
#      password: Bxd@12345


###\u624B\u52A8\u914D\u7F6E\u591A\u6570\u636E\u6E90###
dynamic:
  datasource:
#master
    master:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_one?characterEncoding=utf8&useSSL=false
      username: root
      password: root
#slave1
    slave1:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_two?characterEncoding=utf8&useSSL=false
      username: root
      password: root
